# Generated by Django 5.0.3 on 2024-03-23 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 14, 54, 52, 624024, tzinfo=datetime.timezone.utc)),
        ),
    ]
