# Generated by Django 5.0.3 on 2024-03-17 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_auther_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 13, 35, 28, 203397, tzinfo=datetime.timezone.utc)),
        ),
    ]
