# Generated by Django 5.0.3 on 2024-03-27 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published_at_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 21, 45, 53, 570636, tzinfo=datetime.timezone.utc)),
        ),
    ]
