# Generated by Django 5.0.3 on 2024-04-03 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 11, 1, 9, 230989, tzinfo=datetime.timezone.utc)),
        ),
    ]
