# Generated by Django 5.0.3 on 2024-05-08 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 10, 56, 998753, tzinfo=datetime.timezone.utc)),
        ),
    ]
