# Generated by Django 5.0.3 on 2024-05-11 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_posts_comment_post_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 13, 3, 37, 67899, tzinfo=datetime.timezone.utc)),
        ),
    ]
