# Generated by Django 5.0.3 on 2024-05-16 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 17, 11, 23, 87821, tzinfo=datetime.timezone.utc)),
        ),
    ]
