# Generated by Django 5.0.3 on 2024-05-17 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 12, 22, 5, 864693, tzinfo=datetime.timezone.utc)),
        ),
    ]
