# Generated by Django 5.0.3 on 2024-05-19 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 19, 17, 5, 688277, tzinfo=datetime.timezone.utc)),
        ),
    ]
